(function(){
  const regionData = [
    { "region": "africa-south1", "location": "Johannesburg", "cfe": 0.16, "intensity": 646, "pue": 1.10 },
    { "region": "asia-east1", "location": "Taiwan", "cfe": 0.18, "intensity": 451, "pue": 1.12 },
    { "region": "asia-east2", "location": "Hong Kong", "cfe": 0.28, "intensity": 360, "pue": 1.10 },
    { "region": "asia-northeast1", "location": "Tokyo", "cfe": 0.16, "intensity": 459, "pue": 1.10 },
    { "region": "asia-northeast2", "location": "Osaka", "cfe": 0.30, "intensity": 385, "pue": 1.10 },
    { "region": "asia-northeast3", "location": "Seoul", "cfe": 0.35, "intensity": 378, "pue": 1.10 },
    { "region": "asia-south1", "location": "Mumbai", "cfe": 0.14, "intensity": 648, "pue": 1.10 },
    { "region": "asia-south2", "location": "Delhi", "cfe": 0.29, "intensity": 529, "pue": 1.10 },
    { "region": "asia-southeast1", "location": "Singapore", "cfe": 0.04, "intensity": 369, "pue": 1.12 },
    { "region": "asia-southeast2", "location": "Jakarta", "cfe": 0.13, "intensity": 580, "pue": 1.10 },
    { "region": "australia-southeast1", "location": "Sydney", "cfe": 0.33, "intensity": 501, "pue": 1.10 },
    { "region": "australia-southeast2", "location": "Melbourne", "cfe": 0.40, "intensity": 456, "pue": 1.10 },
    { "region": "europe-central2", "location": "Warsaw", "cfe": 0.31, "intensity": 723, "pue": 1.10 },
    { "region": "europe-north1", "location": "Finland", "cfe": 0.98, "intensity": 46, "pue": 1.09 },
    { "region": "europe-southwest1", "location": "Madrid", "cfe": 0.76, "intensity": 131, "pue": 1.10 },
    { "region": "europe-west1", "location": "Belgium", "cfe": 0.82, "intensity": 122, "pue": 1.09 },
    { "region": "europe-west2", "location": "London", "cfe": 0.92, "intensity": 136, "pue": 1.10 },
    { "region": "europe-west3", "location": "Frankfurt", "cfe": 0.90, "intensity": 345, "pue": 1.10 },
    { "region": "europe-west4", "location": "Netherlands", "cfe": 0.80, "intensity": 236, "pue": 1.09 },
    { "region": "europe-west6", "location": "Zurich", "cfe": 0.92, "intensity": 59, "pue": 1.10 },
    { "region": "europe-west8", "location": "Milan", "cfe": 0.52, "intensity": 249, "pue": 1.10 },
    { "region": "europe-west9", "location": "Paris", "cfe": 0.94, "intensity": 34, "pue": 1.10 },
    { "region": "europe-west10", "location": "Berlin", "cfe": 0.90, "intensity": 345, "pue": 1.10 },
    { "region": "europe-west12", "location": "Turin", "cfe": 0.52, "intensity": 249, "pue": 1.10 },
    { "region": "me-central1", "location": "Doha", "cfe": 0.00, "intensity": 575, "pue": 1.10 },
    { "region": "me-central2", "location": "Dammam", "cfe": 0.00, "intensity": 569, "pue": 1.10 },
    { "region": "me-west1", "location": "Tel Aviv", "cfe": 0.05, "intensity": 463, "pue": 1.10 },
    { "region": "northamerica-northeast1", "location": "Montréal", "cfe": 1.00, "intensity": 2, "pue": 1.10 },
    { "region": "northamerica-northeast2", "location": "Toronto", "cfe": 0.87, "intensity": 47, "pue": 1.10 },
    { "region": "southamerica-east1", "location": "Sāo Paulo", "cfe": 0.90, "intensity": 56, "pue": 1.10 },
    { "region": "southamerica-west1", "location": "Santiago", "cfe": 0.91, "intensity": 138, "pue": 1.10 },
    { "region": "us-central1", "location": "Iowa", "cfe": 0.95, "intensity": 430, "pue": 1.11 },
    { "region": "us-east1", "location": "South Carolina", "cfe": 0.29, "intensity": 560, "pue": 1.11 },
    { "region": "us-east5", "location": "Columbus", "cfe": 0.52, "intensity": 322, "pue": 1.10 },
    { "region": "us-east4", "location": "Northern Virginia", "cfe": 0.52, "intensity": 322, "pue": 1.10 },
    { "region": "us-south1", "location": "Dallas", "cfe": 0.79, "intensity": 321, "pue": 1.10 },
    { "region": "us-west1", "location": "Oregon", "cfe": 0.84, "intensity": 94, "pue": 1.10 },
    { "region": "us-west2", "location": "Los Angeles", "cfe": 0.55, "intensity": 198, "pue": 1.10 },
    { "region": "us-west3", "location": "Salt Lake City", "cfe": 0.29, "intensity": 588, "pue": 1.10 },
    { "region": "us-west4", "location": "Las Vegas", "cfe": 0.26, "intensity": 373, "pue": 1.10 }
  ];
  window.regionData = regionData;
})();
